Test/user api
GetStream/stream-chat-android-client pull request #2
Opened 2020-01-28 14:29 UTC by andriizhumela

- Added tests user api

2020-01-29 11:43 UTC, elevenetc requested changes

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/StreamChatClient.kt
> +package io.getstream.chat.android.core.poc.library
The file should be deleted.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/json/adapters/QuerySortAdapter.kt
> +    override fun write(out: JsonWriter?, value: QuerySort?) {
`out` is not optional.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/json/adapters/QuerySortAdapter.kt
> +        val adapter = Gson().getAdapter(ArrayList::class.java)
There is no need to create instance of `Gson`. See how `FilterObjectAdapter` reuses `Gson` instance.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/json/adapters/QuerySortAdapter.kt
> +        IOException("not supported")
Could you replace message with something more meaningful? Like `QuerySort` must not be deserialised.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/requests/QuerySort.kt
> +@JsonAdapter(QuerySortAdapter::class)
Let's not use `@JsonAdapter`. We need to reuse `Gson` instance without passing around static instance and as far as I know `@JsonAdapter` can't help with it.
I also want to keep everything in single place: `JsonParser`, so even developers who never worked with `Gson` can see and edit everything in a single place.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/requests/QueryUsers.kt
> +    @Expose
No need add everywhere `@Expose`.
The old code used it everywhere because models had mixed fields (app, database, api, etc). Not there're only api fields, so all of them should be exposed.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/requests/QueryUsers.kt
> +    @SerializedName("presence")
There is no need to repeat field name with `@SerializedName` if it's already correct.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/BanUserRequest.kt
> +    @Expose
No need add everywhere `@Expose`.
The old code used it everywhere because models had mixed fields (app, database, api, etc). Not there're only api fields, so all of them should be exposed.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/BanUserRequest.kt
> +    @SerializedName("reason")
There is no need to repeat field name with @SerializedName if it's already correct.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/QueryUserListResponse.kt
> +    @SerializedName("users")
See my message about @SerializedName

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/QueryUserListResponse.kt
> +    @Expose
See my message about Expose

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/GeustUserRequest.kt
> +        @SerializedName("id")
See my message about @SerializedName

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/GeustUserRequest.kt
> +        @Expose
See my message about @Expose

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/api/RetrofitClient.kt
> +    private fun prepareRequest(
The method is not used. It's already applied in interceptor.

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/api/RetrofitClient.kt
> +    private fun createGsonConverter(
The method is not used. It is already applied in `JsonParser`

2020-01-29 11:43 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/ChatClientImpl.kt
> +        anonymousApi.setGuestUser(
That looks bad. Having almost the same instance of api just for one call look wrong.
Maybe there is way to do something like?
```
override fun setGuestUser(
        user: User,
        callback: (Result<ConnectionData>) -> Unit
) {
  api.anonimous = true
  socket.anonimous = true
  //...
}

override fun setUser(
        user: User,
        callback: (Result<ConnectionData>) -> Unit
) {
  api.anonimous = false
  socket.anonimous = true
  //...
}
```

2020-01-29 13:17 UTC, andriizhumela commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/GeustUserRequest.kt
> +        @Expose
@elevenetc  What message?

2020-01-29 13:17 UTC, andriizhumela commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/GeustUserRequest.kt
> +        @SerializedName("id")
@elevenetc  What message?

2020-01-29 13:21 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/GeustUserRequest.kt
> +        @SerializedName("id")
@andriizhumela this one https://github.com/GetStream/stream-chat-android-client/pull/2#discussion_r372323946

2020-01-30 09:37 UTC, andriizhumela commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/GeustUserRequest.kt
> +        @SerializedName("id")
@elevenetc Ok, how would it work if the user turned on code obfuscation?
I don't think that duplication with SerializedName is a mistake.
And forcing the user to add a module with the library as an exception, in my opinion, too, is not entirely correct.

2020-01-30 10:56 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/rest/GeustUserRequest.kt
> +        @SerializedName("id")
There should be a reason to use any annotation. Otherwise it just doesn't make sense and might be harmful and inconvenient:
- A library which covers the whole project with annotations (or base classes like Realm by the way) is already a bad sign. 
- If we decide to replace gson we need to go through the whole library to get rid of annotations. That's again a bad sign if a minor library forces to change the whole project.
- Readability especially with Kotlin goes down. Data class with 10 lines automatically becomes 20 lines of repeated test. With `@Expose` it becomes 30 lines.
- Annotation processor will just go through all fields in the project and do nothing literally. When build pipeline tool does nothing it's another bad sign.

About obfuscation I'm not sure that proguard (or any other tool) obfuscates libraries of an app by default. That would break just lots of libraries automatically. Modern apps have massive dependencies trees, lots of them are open source and again it just doesn't make sense to obfuscate them. Obfuscation is a problem of source code owner, not client who uses it. Even if it is obfuscated by default excluding is fine.

2020-01-30 15:11 UTC, elevenetc requested changes
Everything is ok except `App`. I divided explicitly package:
- `io.getstream.chat.android.core.poc.app` will be removed. Right now it is just for convenience.
- `io.getstream.chat.android.core.poc.library` is actual library. It shouldn't contain anything from app.

2020-01-30 15:11 UTC, elevenetc commented on app/src/main/java/io/getstream/chat/android/core/poc/library/ChatApiImpl.kt
> +    private val application: App
There should not be `App`. `App` is just testing code, it will be removed from library.

2020-01-31 12:47 UTC, elevenetc approved these changes

2020-01-31 12:54 UTC, merged