Test custom fields serializing and deserializing
GetStream/stream-chat-android-client pull request #77
Opened 2020-09-17 14:43 UTC by samiuelson

2020-09-17 20:43 UTC, tschellenbach commented
👏

2020-09-18 06:34 UTC, zsmb13 requested changes
Looks good overall, left some comments.

2020-09-18 06:34 UTC, zsmb13 commented on client/src/main/java/io/getstream/chat/android/client/parser/adapters/CustomObjectGsonAdapter.kt
> +                obj.extraData.forEach { result[it.key] = it.value }
I think this is just `result.putAll(obj.extraData)`? (Which is also `result += obj.extraData`, if you want to be fancy)

2020-09-18 06:34 UTC, zsmb13 commented on client/src/test/java/io/getstream/chat/android/client/parser/adapters/CustomObjectAdapterTest.kt
> +    }
Couldn't this be a single test itself, which fails on its own if the check in it fails, instead of failing all tests here?

2020-09-18 06:34 UTC, zsmb13 commented on client/src/test/java/io/getstream/chat/android/client/parser/adapters/CustomObjectAdapterTest.kt
> +            get("extraData").asJsonObject.apply {
All this nesting of `apply` calls usually gets messy, but in this case it's actually super readable. Really nicely done! 👍

2020-09-18 06:34 UTC, zsmb13 commented on client/src/test/java/io/getstream/chat/android/client/parser/adapters/CustomObjectAdapterTest.kt
> +        const val json = "{\n  \"id\": \"8584452-6d711169-0224-41c2-b9aa-1adbe624521b\",\n  \"extraData\": {\n    \"key1\": \"value1\",\n    \"key2\": true,\n    \"key3\": {\n      \"key4\": \"val4\"
```suggestion
        const val json = """{
          "id": "8584452-6d711169-0224-41c2-b9aa-1adbe624521b",
          "extraData": {
            "key1": "value1",
            "key2": true,
            "key3": {
              "key4": "val4"
            }
          },
          "customKey1": "customVal1",
          "customKey2": "customVal2",
          "customKey3": true,
          "customKey4": [
            "a",
            "b",
            "c"
          ]
        }"""
```

2020-09-18 09:02 UTC, zsmb13 approved these changes

2020-09-18 10:03 UTC, merged